//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWCFPersonasCliente.ServiceReferencePersonas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntPersonas", Namespace="http://schemas.datacontract.org/2004/07/EntityPersonas")]
    [System.SerializableAttribute()]
    public partial class EntPersonas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((this.FechaAltaField.Equals(value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePersonas.IServicePersonas")]
    public interface IServicePersonas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePersonas/Obtener", ReplyAction="http://tempuri.org/IServicePersonas/ObtenerResponse")]
        WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas[] Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePersonas/Obtener", ReplyAction="http://tempuri.org/IServicePersonas/ObtenerResponse")]
        System.Threading.Tasks.Task<WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas[]> ObtenerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePersonas/ObtenerPorId", ReplyAction="http://tempuri.org/IServicePersonas/ObtenerPorIdResponse")]
        WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas ObtenerPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePersonas/ObtenerPorId", ReplyAction="http://tempuri.org/IServicePersonas/ObtenerPorIdResponse")]
        System.Threading.Tasks.Task<WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas> ObtenerPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePersonas/Agregar", ReplyAction="http://tempuri.org/IServicePersonas/AgregarResponse")]
        void Agregar(WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePersonas/Agregar", ReplyAction="http://tempuri.org/IServicePersonas/AgregarResponse")]
        System.Threading.Tasks.Task AgregarAsync(WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePersonasChannel : WebWCFPersonasCliente.ServiceReferencePersonas.IServicePersonas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePersonasClient : System.ServiceModel.ClientBase<WebWCFPersonasCliente.ServiceReferencePersonas.IServicePersonas>, WebWCFPersonasCliente.ServiceReferencePersonas.IServicePersonas {
        
        public ServicePersonasClient() {
        }
        
        public ServicePersonasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePersonasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePersonasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas[] Obtener() {
            return base.Channel.Obtener();
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas[]> ObtenerAsync() {
            return base.Channel.ObtenerAsync();
        }
        
        public WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas ObtenerPorId(int id) {
            return base.Channel.ObtenerPorId(id);
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas> ObtenerPorIdAsync(int id) {
            return base.Channel.ObtenerPorIdAsync(id);
        }
        
        public void Agregar(WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas p) {
            base.Channel.Agregar(p);
        }
        
        public System.Threading.Tasks.Task AgregarAsync(WebWCFPersonasCliente.ServiceReferencePersonas.EntPersonas p) {
            return base.Channel.AgregarAsync(p);
        }
    }
}
